#!/bin/bash
#author:david baudet moreno

cat /etc/passwd > /home/david/listado

while read linea
do
        numerouid=`echo ${linea} | cut -d ":" -f3`

        if [ ${1} -eq ${numerouid} ]
        then
                echo "el usuario existe"
		
        fi


done < /home/david/listado

