#!/bin/bash
#author:david baudet moreno

ls ~/${2} > /tmp/temporal
contador=0
comprimidos=0
while read linea
do
	if [ ! -d ~/${2}/${linea} ]
	then
		lineatotal=${lineatotal}" "${linea}
		comprimidos=$(( ${comprimidos} + 1 ))
	else
		contador=$(( ${contador} + 1 ))	
	fi

done < /tmp/temporal
tar czf ~/${2}/${1}."tar".gz ${lineatotal}
echo ${contador} carpetas
echo ${comprimidos} comprimidos
