/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smma.juegosTablero.gui;

import juegosTablero.dominio.elementos.ClasificacionJuego;
import juegosTablero.dominio.elementos.Jugador;
import java.util.Iterator;

/**
 *
 * @author pedroj
 */
public class ClasificacionJuegoJFrame extends javax.swing.JFrame {
    /**
     * Creates new form AgentesJuegoJFrame
     */
    public ClasificacionJuegoJFrame(ClasificacionJuego clasificacion) {
        initComponents();
        
        this.setTitle("Clasificación: " + clasificacion.getJuego().getIdJuego());
        presentar(clasificacion);
        this.setVisible(true);
        
    }
    
    private void presentar(ClasificacionJuego clasificacion) {
       Iterator itJugador = clasificacion.getListaJugadores().iterator();
       Iterator itPuntuacion = clasificacion.getListaPuntuacion().iterator();
       
       int puesto = 1;
       while ( itJugador.hasNext() ) {
           Jugador jugador = (Jugador) itJugador.next();
           long puntos = (Long) itPuntuacion.next();
           String vistaJugador = String.format("%2d", puesto) + "º " + jugador.getNombre() + "\n";
           String vistaPuntos = String.format("%10d", puntos) + "\n";
           
           agentesJugador.append(vistaJugador);
           puntuacion.append(vistaPuntos);
           puesto++;
       }
        
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        agentesJugador = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        puntuacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Jugadores");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Puntuación");

        agentesJugador.setEditable(false);
        agentesJugador.setColumns(20);
        agentesJugador.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        agentesJugador.setRows(5);
        jScrollPane2.setViewportView(agentesJugador);

        puntuacion.setEditable(false);
        puntuacion.setColumns(10);
        puntuacion.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        puntuacion.setRows(5);
        jScrollPane4.setViewportView(puntuacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea agentesJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea puntuacion;
    // End of variables declaration//GEN-END:variables
}
